qr-code:
  qrCodeRepository: E://qr-code-repos
  logoRepository: E://qr-code-repos/logo
  bgRepository: E://qr-code-repos/bg

  cardTemplates:
    defaultTemplate:
      render_class: com.bx.card.render.DefaultCardRender
      bg_img: bx_bg.jpg
      head_img: bx_hd.png
      user_name_key: user_name

spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${qr-code.qrCodeRepository}/
